// @generated by generate_ptr_flags.rs.py � do not edit

pub fn pointer_flags(sysno: u32) -> Option<&'static [bool]> {

    match sysno {

        0 => Some(&[false, true, false]),

        1 => Some(&[false, true, false]),

        2 => Some(&[true, false, false]),

        3 => Some(&[false]),

        4 => Some(&[true, true]),

        5 => Some(&[false, true]),

        6 => Some(&[true, true]),

        7 => Some(&[true, false, false]),

        8 => Some(&[false, false, false]),

        9 => Some(&[false, false, false, false, false, false]),

        10 => Some(&[false, false, false]),

        11 => Some(&[false, false]),

        12 => Some(&[false]),

        13 => Some(&[false, true, true, false]),

        14 => Some(&[false, true, true, false]),

        15 => Some(&[]),

        16 => Some(&[false, false, false]),

        17 => Some(&[false, true, false, false]),

        18 => Some(&[false, true, false, false]),

        19 => Some(&[false, true, false]),

        20 => Some(&[false, true, false]),

        21 => Some(&[true, false]),

        22 => Some(&[true]),

        23 => Some(&[false, true, true, true, true]),

        24 => Some(&[]),

        25 => Some(&[false, false, false, false, false]),

        26 => Some(&[false, false, false]),

        27 => Some(&[false, false, true]),

        28 => Some(&[false, false, false]),

        29 => Some(&[false, false, false]),

        30 => Some(&[false, true, false]),

        31 => Some(&[false, false, true]),

        32 => Some(&[false]),

        33 => Some(&[false, false]),

        34 => Some(&[]),

        35 => Some(&[true, true]),

        36 => Some(&[false, true]),

        37 => Some(&[false]),

        38 => Some(&[false, true, true]),

        39 => Some(&[]),

        40 => Some(&[false, false, true, false]),

        41 => Some(&[false, false, false]),

        42 => Some(&[false, true, false]),

        43 => Some(&[false, true, true]),

        44 => Some(&[false, true, false, false, true, false]),

        45 => Some(&[false, true, false, false, true, true]),

        46 => Some(&[false, true, false]),

        47 => Some(&[false, true, false]),

        48 => Some(&[false, false]),

        49 => Some(&[false, true, false]),

        50 => Some(&[false, false]),

        51 => Some(&[false, true, true]),

        52 => Some(&[false, true, true]),

        53 => Some(&[false, false, false, true]),

        54 => Some(&[false, false, false, true, false]),

        55 => Some(&[false, false, false, true, true]),

        56 => Some(&[false, false, true, false, true]),

        57 => Some(&[]),

        58 => Some(&[]),

        59 => Some(&[true, true, true]),

        60 => Some(&[false]),

        61 => Some(&[false, true, false, true]),

        62 => Some(&[false, false]),

        63 => Some(&[true]),

        64 => Some(&[false, false, false]),

        65 => Some(&[false, true, false]),

        66 => Some(&[false, false, false, false]),

        67 => Some(&[true]),

        68 => Some(&[false, false]),

        69 => Some(&[false, true, false, false]),

        70 => Some(&[false, true, false, false, false]),

        71 => Some(&[false, false, true]),

        72 => Some(&[false, false, false]),

        73 => Some(&[false, false]),

        74 => Some(&[false]),

        75 => Some(&[false]),

        76 => Some(&[true, false]),

        77 => Some(&[false, false]),

        78 => Some(&[false, true, false]),

        79 => Some(&[true, false]),

        80 => Some(&[true]),

        81 => Some(&[false]),

        82 => Some(&[true, true]),

        83 => Some(&[true, false]),

        84 => Some(&[true]),

        85 => Some(&[true, false]),

        86 => Some(&[true, true]),

        87 => Some(&[true]),

        88 => Some(&[true, true]),

        89 => Some(&[true, true, false]),

        90 => Some(&[true, false]),

        91 => Some(&[false, false]),

        92 => Some(&[true, false, false]),

        93 => Some(&[false, false, false]),

        94 => Some(&[true, false, false]),

        95 => Some(&[false]),

        96 => Some(&[true, true]),

        97 => Some(&[false, true]),

        98 => Some(&[false, true]),

        99 => Some(&[true]),

        100 => Some(&[true]),

        101 => Some(&[false, false, false, false]),

        102 => Some(&[]),

        103 => Some(&[false, true, false]),

        104 => Some(&[]),

        105 => Some(&[false]),

        106 => Some(&[false]),

        107 => Some(&[]),

        108 => Some(&[]),

        109 => Some(&[false, false]),

        110 => Some(&[]),

        111 => Some(&[]),

        112 => Some(&[]),

        113 => Some(&[false, false]),

        114 => Some(&[false, false]),

        115 => Some(&[false, true]),

        116 => Some(&[false, true]),

        117 => Some(&[false, false, false]),

        118 => Some(&[true, true, true]),

        119 => Some(&[false, false, false]),

        120 => Some(&[true, true, true]),

        121 => Some(&[false]),

        122 => Some(&[false]),

        123 => Some(&[false]),

        124 => Some(&[false]),

        125 => Some(&[false, false]),

        126 => Some(&[false, false]),

        127 => Some(&[true, false]),

        128 => Some(&[true, true, true, false]),

        129 => Some(&[false, false, true]),

        130 => Some(&[true, false]),

        131 => Some(&[true, true]),

        132 => Some(&[true, true]),

        133 => Some(&[true, false, false]),

        135 => Some(&[false]),

        136 => Some(&[false, true]),

        137 => Some(&[true, true]),

        138 => Some(&[false, true]),

        139 => Some(&[false, false, false]),

        140 => Some(&[false, false]),

        141 => Some(&[false, false, false]),

        142 => Some(&[false, true]),

        143 => Some(&[false, true]),

        144 => Some(&[false, false, true]),

        145 => Some(&[false]),

        146 => Some(&[false]),

        147 => Some(&[false]),

        148 => Some(&[false, true]),

        149 => Some(&[false, false]),

        150 => Some(&[false, false]),

        151 => Some(&[false]),

        152 => Some(&[]),

        153 => Some(&[]),

        154 => Some(&[false, true, false]),

        155 => Some(&[true, true]),

        157 => Some(&[false, false, false, false, false]),

        158 => Some(&[false, false]),

        159 => Some(&[true]),

        160 => Some(&[false, true]),

        161 => Some(&[true]),

        162 => Some(&[]),

        163 => Some(&[true]),

        164 => Some(&[true, true]),

        165 => Some(&[true, true, true, false, true]),

        167 => Some(&[true, false]),

        168 => Some(&[true]),

        169 => Some(&[false, false, false, true]),

        170 => Some(&[true, false]),

        171 => Some(&[true, false]),

        172 => Some(&[false]),

        173 => Some(&[false, false, false]),

        175 => Some(&[true, false, true]),

        176 => Some(&[true, false]),

        179 => Some(&[false, true, false, true]),

        186 => Some(&[]),

        187 => Some(&[false, false, false]),

        188 => Some(&[true, true, true, false, false]),

        189 => Some(&[true, true, true, false, false]),

        190 => Some(&[false, true, true, false, false]),

        191 => Some(&[true, true, true, false]),

        192 => Some(&[true, true, true, false]),

        193 => Some(&[false, true, true, false]),

        194 => Some(&[true, true, false]),

        195 => Some(&[true, true, false]),

        196 => Some(&[false, true, false]),

        197 => Some(&[true, true]),

        198 => Some(&[true, true]),

        199 => Some(&[false, true]),

        200 => Some(&[false, false]),

        201 => Some(&[true]),

        202 => Some(&[true, false, false, true, true, false]),

        203 => Some(&[false, false, true]),

        204 => Some(&[false, false, true]),

        206 => Some(&[false, true]),

        207 => Some(&[false]),

        208 => Some(&[false, false, false, true, true]),

        209 => Some(&[false, false, true]),

        210 => Some(&[false, true, true]),

        213 => Some(&[false]),

        216 => Some(&[false, false, false, false, false]),

        217 => Some(&[false, true, false]),

        218 => Some(&[true]),

        219 => Some(&[]),

        220 => Some(&[false, true, false, true]),

        221 => Some(&[false, false, false, false]),

        222 => Some(&[false, true, true]),

        223 => Some(&[false, false, true, true]),

        224 => Some(&[false, true]),

        225 => Some(&[false]),

        226 => Some(&[false]),

        227 => Some(&[false, true]),

        228 => Some(&[false, true]),

        229 => Some(&[false, true]),

        230 => Some(&[false, false, true, true]),

        231 => Some(&[false]),

        232 => Some(&[false, true, false, false]),

        233 => Some(&[false, false, false, true]),

        234 => Some(&[false, false, false]),

        235 => Some(&[true, true]),

        237 => Some(&[false, false, false, true, false, false]),

        238 => Some(&[false, true, false]),

        239 => Some(&[true, true, false, false, false]),

        240 => Some(&[true, false, false, true]),

        241 => Some(&[true]),

        242 => Some(&[false, true, false, false, true]),

        243 => Some(&[false, true, false, true, true]),

        244 => Some(&[false, true]),

        245 => Some(&[false, true, true]),

        246 => Some(&[false, false, true, false]),

        247 => Some(&[false, false, true, false, true]),

        248 => Some(&[true, true, true, false, false]),

        249 => Some(&[true, true, true, false]),

        250 => Some(&[false, false, false, false, false]),

        251 => Some(&[false, false, false]),

        252 => Some(&[false, false]),

        253 => Some(&[]),

        254 => Some(&[false, true, false]),

        255 => Some(&[false, false]),

        256 => Some(&[false, false, true, true]),

        257 => Some(&[false, true, false, false]),

        258 => Some(&[false, true, false]),

        259 => Some(&[false, true, false, false]),

        260 => Some(&[false, true, false, false, false]),

        261 => Some(&[false, true, true]),

        262 => Some(&[false, true, true, false]),

        263 => Some(&[false, true, false]),

        264 => Some(&[false, true, false, true]),

        265 => Some(&[false, true, false, true, false]),

        266 => Some(&[true, false, true]),

        267 => Some(&[false, true, true, false]),

        268 => Some(&[false, true, false]),

        269 => Some(&[false, true, false]),

        270 => Some(&[false, true, true, true, true, true]),

        271 => Some(&[true, false, true, true, false]),

        272 => Some(&[false]),

        273 => Some(&[true, false]),

        274 => Some(&[false, true, true]),

        275 => Some(&[false, true, false, true, false, false]),

        276 => Some(&[false, false, false, false]),

        277 => Some(&[false, false, false, false]),

        278 => Some(&[false, true, false, false]),

        279 => Some(&[false, false, true, true, true, false]),

        280 => Some(&[false, true, true, false]),

        281 => Some(&[false, true, false, false, true, false]),

        282 => Some(&[false, true, false]),

        283 => Some(&[false, false]),

        284 => Some(&[false]),

        285 => Some(&[false, false, false, false]),

        286 => Some(&[false, false, true, true]),

        287 => Some(&[false, true]),

        288 => Some(&[false, true, true, false]),

        289 => Some(&[false, true, false, false]),

        290 => Some(&[false, false]),

        291 => Some(&[false]),

        292 => Some(&[false, false, false]),

        293 => Some(&[true, false]),

        294 => Some(&[false]),

        295 => Some(&[false, true, false, false, false]),

        296 => Some(&[false, true, false, false, false]),

        297 => Some(&[false, false, false, true]),

        298 => Some(&[true, false, false, false, false]),

        299 => Some(&[false, true, false, false, true]),

        300 => Some(&[false, false]),

        301 => Some(&[false, false, false, false, true]),

        302 => Some(&[false, false, true, true]),

        303 => Some(&[false, true, true, true, false]),

        304 => Some(&[false, true, false]),

        305 => Some(&[false, true]),

        306 => Some(&[false]),

        307 => Some(&[false, true, false, false]),

        308 => Some(&[false, false]),

        309 => Some(&[true, true, true]),

        310 => Some(&[false, true, false, true, false, false]),

        311 => Some(&[false, true, false, true, false, false]),

        312 => Some(&[false, false, false, false, false]),

        313 => Some(&[false, true, false]),

        314 => Some(&[false, true, false]),

        315 => Some(&[false, true, false, false]),

        316 => Some(&[false, true, false, true, false]),

        317 => Some(&[false, false, true]),

        318 => Some(&[true, false, false]),

        319 => Some(&[true, false]),

        320 => Some(&[false, false, false, true, false]),

        321 => Some(&[false, true, false]),

        322 => Some(&[false, true, true, true, false]),

        323 => Some(&[false]),

        324 => Some(&[false, false, false]),

        325 => Some(&[false, false, false]),

        326 => Some(&[false, true, false, true, false, false]),

        327 => Some(&[false, true, false, false, false, false]),

        328 => Some(&[false, true, false, false, false, false]),

        329 => Some(&[false, false, false, false]),

        330 => Some(&[false, false]),

        331 => Some(&[false]),

        332 => Some(&[false, true, false, false, true]),

        333 => Some(&[false, false, false, true, true, true]),

        334 => Some(&[true, false, false, false]),

        335 => Some(&[]),

        424 => Some(&[false, false, true, false]),

        425 => Some(&[false, true]),

        426 => Some(&[false, false, false, false, true, false]),

        427 => Some(&[false, false, true, false]),

        428 => Some(&[false, true, false]),

        429 => Some(&[false, true, false, true, false]),

        430 => Some(&[true, false]),

        431 => Some(&[false, false, true, true, false]),

        432 => Some(&[false, false, false]),

        433 => Some(&[false, true, false]),

        434 => Some(&[false, false]),

        435 => Some(&[true, false]),

        436 => Some(&[false, false, false]),

        437 => Some(&[false, true, true, false]),

        438 => Some(&[false, false, false]),

        439 => Some(&[false, true, false, false]),

        440 => Some(&[false, true, false, false, false]),

        441 => Some(&[false, true, false, true, true, false]),

        442 => Some(&[false, true, false, true, false]),

        443 => Some(&[false, false, false, true]),

        444 => Some(&[true, false, false]),

        445 => Some(&[false, false, true, false]),

        446 => Some(&[false, false]),

        447 => Some(&[false]),

        448 => Some(&[false, false]),

        449 => Some(&[true, false, false, true, false]),

        450 => Some(&[false, false, false, false]),

        451 => Some(&[false, true, true, false]),

        452 => Some(&[false, true, false, false]),

        453 => Some(&[false, false, false]),

        454 => Some(&[true, false, false, false]),

        455 => Some(&[true, false, false, false, true, false]),

        456 => Some(&[true, false, false, false]),

        457 => Some(&[true, true, false, false]),

        458 => Some(&[true, true, false, false]),

        459 => Some(&[false, true, true, false]),

        460 => Some(&[false, true, false, false]),

        461 => Some(&[true, true, false]),

        462 => Some(&[false, false, false]),

        463 => Some(&[false, true, false, true, true, false]),

        464 => Some(&[false, true, false, true, true, false]),

        465 => Some(&[false, true, false, true, false]),

        466 => Some(&[false, true, false, true]),

        467 => Some(&[false, true, false, true, false]),

        512 => Some(&[false, true, true, false]),

        513 => Some(&[]),

        514 => Some(&[false, false, false]),

        515 => Some(&[false, true, false]),

        516 => Some(&[false, true, false]),

        517 => Some(&[false, true, false, false, true, true]),

        518 => Some(&[false, true, false]),

        519 => Some(&[false, true, false]),

        520 => Some(&[true, true, true]),

        521 => Some(&[false, false, false, false]),

        522 => Some(&[true, false]),

        523 => Some(&[true, true, true, false]),

        524 => Some(&[false, false, true]),

        525 => Some(&[true, true]),

        526 => Some(&[false, true, true]),

        527 => Some(&[false, true]),

        528 => Some(&[false, false, true, false]),

        529 => Some(&[false, false, true, false, true]),

        530 => Some(&[true, false]),

        531 => Some(&[false, true, true]),

        532 => Some(&[false, true, false, false]),

        533 => Some(&[false, false, true, true, true, false]),

        534 => Some(&[false, true, false, false, false]),

        535 => Some(&[false, true, false, false, false]),

        536 => Some(&[false, false, false, true]),

        537 => Some(&[false, true, false, false, true]),

        538 => Some(&[false, true, false, false]),

        539 => Some(&[false, true, false, true, false, false]),

        540 => Some(&[false, true, false, true, false, false]),

        541 => Some(&[false, false, false, true, false]),

        542 => Some(&[false, false, false, true, true]),

        543 => Some(&[false, true]),

        544 => Some(&[false, false, true]),

        545 => Some(&[false, true, true, true, false]),

        546 => Some(&[false, true, false, false, false, false]),

        547 => Some(&[false, true, false, false, false, false]),

        _ => None,

    }

}

